name: CI
on:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # cache node_modules
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # setup node
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
      # npm ci
      - run: npm ci
      - name: Use Docker
        uses: docker-practice/actions-setup-docker@master
      - name: Build & Save Docker Image
        run: |
          docker build . -t mauju/simple-express
          mkdir build
          docker save mauju/simple-express | gzip > build/mauju-simple-express.tar.gz
      - name: Deploy Docker Image to VPS
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
      - name: Load Docker Images on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ../home/mauju.com/docker-images
            ls -la
            docker load --input mauju-simple-express.tar.gz